test:
	go test ./...

run-service:
	docker-compose -f deploy/docker-compose.yaml up -d

stop-service:
	docker-compose -f deploy/docker-compose.yaml down


run-service-only:
	docker build -t url-shortener -f deploy/Dockerfile .
	docker run --env-file config/.env url-shortener